name: First workflow - push commit - 1 job
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: instala dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: desploy 
        run: echo "deployed OK"
  
