name: First workflow - push commit - 3 jobs 
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: echo "lint OK"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test
      - run: echo "test OK"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "deployed OK"
