name: test variables y secretos

on:
  push:
    branches:
      - main

jobs:
  variablesEntornoCodigo:
    runs-on: ubuntu-latest
    env:
      v1: 'variable desde codigo'
    steps:
      - run: echo ${{ env.v1 }}

  variablesEntornoConfigRepo:
    needs: variablesEntornoCodigo
    runs-on: ubuntu-latest    
    steps:
      - run: echo ${{ env.V2 }}

  secretos:
    runs-on: ubuntu-latest
    needs: variablesEntornoCodigo
    env:
      v1: 'secretos'
    steps:
      - run: echo ${{ secrets.S1 }}